version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.1-node-browsers
        environment:
          TEST_DATABASE_URL: postgresql://sharing@localhost/sharing_test
          PGHOST: 127.0.0.1
          RAILS_ENV: test
      - image: circleci/postgres:9.5-alpine-postgis
        environment:
          POSTGRES_USER: circleci
          POSTGRES_DB: sharing_test
        
    steps:
      - checkout
      - run: gem install bundler:2.0.1
      - run: bundle install
      - run: rails db:create
      - run: rails db:migrate
      - run: bundle exec rspec
      - run: bundle exec slim-lint app/*
      - run: rubocop
